version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "9229:9229"

  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vaccinescheduler
      POSTGRES_USER: vaccineadmin
      POSTGRES_PASSWORD: admin#123
